### ISSUE TITLE
Running Fione Question

### ISSUE THREAD

**Issue by gabfields02** [codelibs/docker-fione#1]
Hi. I tried to run Fione using the steps mentioned here. 
![image](https://user-images.githubusercontent.com/55271708/80469666-74ad9a00-8973-11ea-965d-7f100696a016.png)

However, after running "docker-compose up", it just stops here and I cannot access Fione.
![image](https://user-images.githubusercontent.com/55271708/80938099-65629c80-8e0a-11ea-8a54-0abeed624200.png)

Can you help me on how to run Fione?

**Comment by marevol** [comment]
`master` branch is a snapshot version. please specify a tag name:
```
$ git clone https://github.com/codelibs/docker-fione.git -b v13.6.2
```

**Comment by gabfields02** [comment]
> `master` branch is a snapshot version. please specify a tag name:
> 
> ```
> $ git clone https://github.com/codelibs/docker-fione.git -b v13.6.2
> ```

Thank you. I just recently specified a tag name now. 
I have the following running on my Docker and I can access the first three.
![image](https://user-images.githubusercontent.com/55271708/80955034-1bd97800-8e31-11ea-8e41-5d3daef88e02.png)

However, I still cannot access this link: 
http://localhost:8080/admin/easyml/

Any ideas on this please?

**Comment by marevol** [comment]
A docker for elasticsearch may need some settings. please see [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144).

**Comment by gabfields02** [comment]
> A docker for elasticsearch may need some settings. please see [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144).

Thank you. I think I have it up and running at this point.

Another question, though. I want to try Create Project. However, when accessing http://localhost:8080/admin/easyml/, it redirects to a Fess login. Is this correct?
![image](https://user-images.githubusercontent.com/55271708/81258712-e323e380-9068-11ea-94b2-40363300a942.png)

And when I try to login as fione user with fione password in the Fess login, it does not go through.
Is there something else I still need to for this?

**Comment by marevol** [comment]
Hmm, I could not reproduce it... Could you try the following steps?

1. Run `docker-compose down`
1. Run `docker volume rm fess-data es-data es-dict minio-data`
1. Run `docker-compose up`
1. Access to `http://localhost:8080/admin/easyml/`
1. Login as `fione` user(password: `fione`). If you cannot login, use `admin` user(password: `admin`)

**Comment by gabfields02** [comment]
Initially, the steps I performed were the following:
1. `git clone   https://github.com/codelibs/docker-fione.git -b v13.6.2`
2. `cd   docker-fione/compose`
3. `docker-compose up`

Then I tried the steps you mentioned. 
> 1. Run `docker-compose down`
> 2. Run `docker volume rm fess-data es-data es-dict minio-data`


However, for some reason, running `docker volume rm fess-data es-data es-dict minio-data` gives me this error though.
![image](https://user-images.githubusercontent.com/55271708/81274063-64d43b00-9082-11ea-90a1-ae2b8e757d0a.png)

**Comment by marevol** [comment]
You can ignore these errors. it's to purge old data.

**Comment by gabfields02** [comment]
Okay, thanks. Currently trying to access `http://localhost:8080/admin/easyml/`. For some reason, it takes so much time to load up. Will get back here when it does.

**Comment by gabfields02** [comment]
Accessing `http://localhost:8080/admin/easyml/` redirected me to `http://localhost:8080/login`.

![image](https://user-images.githubusercontent.com/55271708/81282778-39574d80-908e-11ea-8dc3-e81c6669b792.png)

And logging in as user fione with password fione gives me this error.
![image](https://user-images.githubusercontent.com/55271708/81283630-8a1b7600-908f-11ea-9687-a2d70a40c89f.png)

Trying to login as admin however, `localhost:8080/admin/easyml/` seems to be responding very slowly. The rest of the links `http://localhost:9200/`, `http://localhost:9000/minio/login`, `http://localhost:54321/flow/index.html` responds slightly faster.
Is this slow response normal? Apologies for the many questions. I am kind of new to this.

**Comment by marevol** [comment]
What is a log message in the console?
By the way, is your environment Windows? I checked Fione on docker for Ubuntu and Mac.

**Comment by gabfields02** [comment]
> By the way, is your environment Windows? I checked Fione on docker for Ubuntu and Mac.

Yes, my environment is Windows. I am also using Docker Desktop for Windows.



> What is a log message in the console?

After loading for more than 1 hour, this displayed. 
There is `CurlException: Failed to access to http://es01:9200`. 
There is also a `ConnectException` at the end. 
What could be the possible cause of this?
![image](https://user-images.githubusercontent.com/55271708/81365685-64d44980-911b-11ea-900f-b5b008887305.png)

**Comment by marevol** [comment]
I do not think elasticsearch works...
I installed Docker Desktop into Windows 10 Home and tried Fione.
It works.

1. Set `vm.max_map_count`
    wsl -d docker-desktop
    sysctl -w vm.max_map_count=262144
1. Run Fione
    git clone https://github.com/codelibs/docker-fione.git -b v13.6.2
    cd docker-fione/compose
    docker-compose up
1. Access `http://localhost:8080/admin/easyml/` and login as `fione`

**Comment by gabfields02** [comment]
I think setting the `vm.max_map_count` fixed it for me.
Btw, I also switched to a Linux environment.

Thank you, @marevol
