### ISSUE TITLE
MinIO and H2O Flow Question

### ISSUE THREAD

**Issue by gabfields02** [codelibs/docker-fione#2]
Hello. I could not find much documentation about Fione and I have blocking for investigation.

1. Can I ask how MinIO and H2O Flow is related to Fione?

2. Is there a way to know where to get Access Key and Secret Key for MinIO?
![image](https://user-images.githubusercontent.com/55271708/83491121-d5d10c00-a4e3-11ea-848e-1f335828c489.png)

3. Can the projects (or data such as frames and models) that I have in Fione be connected to H2O Flow? Or are they separate?

**Comment by marevol** [comment]
H2O, MinIO and Elasticsearch is a backend system for Fione.
So, Fione user does not need to touch them.
In H2O Flow(http://localhost:54321/flow/), you can access H2OFrame you create in Fione.

**Comment by gabfields02** [comment]
Thank you, @marevol.
Will try to investigate further on this.
